version: "3.8"
services:
  alpaca-bot:
    build: .
    container_name: alpaca-swing-bot
    restart: unless-stopped
    environment:
      - ALPACA_LIVE_API_KEY=AKRG978ZNISA817UNE1C
      - ALPACA_LIVE_API_SECRET=1mCvTHCR95ZJAcmvElQbGUf1umowwbm5dnEoyfB0
      - STOCK_SYMBOL=NVDA
      - CRYPTO_SYMBOL=LTC/USD
      - STOCK_QUANTITY=1
      - CRYPTO_QUANTITY=0.1
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
